[customizations.installer.kickstart]
contents = """
%post
bootc switch --transport --enforce-container-sigpolicy registry ghcr.io/lightprod/bazzite-htpc:testing
FLATPAK_LIST=$(< /usr/share/ublue-os/bazzite/flatpak/install)
flatpak install --system --assumeyes ${FLATPAK_LIST}
%end
"""

[customizations.installer.modules]
enable = [
  "org.fedoraproject.Anaconda.Modules.Localization",
  "org.fedoraproject.Anaconda.Modules.Storage",
  "org.fedoraproject.Anaconda.Modules.Network",
  "org.fedoraproject.Anaconda.Modules.Security",
  "org.fedoraproject.Anaconda.Modules.Services",
  "org.fedoraproject.Anaconda.Modules.Users",
  "org.fedoraproject.Anaconda.Modules.Timezone",
  "org.fedoraproject.Anaconda.Modules.Runtime"
]
disable = [
  "org.fedoraproject.Anaconda.Modules.Subscription"
]
